### ISSUE TITLE
`may` mistranscribed as `many`?

### ISSUE THREAD

**Issue by mlinksva** [singlecla/singlecla#2]
https://github.com/singlecla/singlecla/blob/0225bfdaff1acd1bcbc4f8c250c8042954c9798d/cla.md#company-and-client-clas

> If a project steward asks me to help get a CLA from someone who **many** own legal rights in my contribution, I promise to help the project steward request that CLA. I am aware that only people with legal authority can sign CLAs on behalf of companies and other legal entities.

I suspect `many` should be `may`; it was before https://github.com/singlecla/singlecla/commit/1ceff33654c389867c377c36315262b8eaaabb11#diff-845e861d4672ddec7192f09634be31b467d9b6b4aff47579bdb92e3876269989R85

**Comment by kemitchell** [comment]
Thanks, @mlinksva!
