### ISSUE TITLE
Limited to permissively licensed others' work even when other terms would be OK?

### ISSUE THREAD

**Issue by mlinksva** [singlecla/singlecla#3]
https://github.com/singlecla/singlecla/blob/0225bfdaff1acd1bcbc4f8c250c8042954c9798d/cla.md#others-work

> When I make contributions including others' work:
> I promise to take basic steps to make sure that work is licensed under permissive open license terms that Blue Oak Council rates "bronze" or better at https://blueoakcouncil.org/list.

Perhaps this is intentional, but in case not, or I'm misunderstanding -- it seems like this agreement couldn't be used say for a contribution to a MPL-2.0 (just to pick a random copyleft license) that includes others' MPL-2.0 licensed work, and that this might be unnecessarily limiting.

**Comment by kemitchell** [comment]
This is great feedback.

The intent here was that contributors should check to see if things are permissive, flag anything that's not, and in any event make sure they keep copyright and license notices in order, so it's clear what's coming in under what terms. But I can definitely read it as you did, and that's a problem.

**Comment by mlinksva** [comment]
Left a comment on the PR, but now I'm thinking of the sort of project that wants a CLA, and those that are copyleft, typically don't want copylefted contributions, but rather permissive, ideally as provided in the "My Own Work" section, and indeed through not strictly as as condition of this CLA applying "for a project that gathers rights to license contributions in a single project steward, such as a foundation, company, or lead developer"

So it seems to me I've identified a non-issue and #4 is not needed.

**Comment by kemitchell** [comment]
@mlinksva I agree that fewer copyleft project stewards will likely want a CLA. Some will just rely on the copyleft requirements of their public licenses, and seek to "lock the project open" by avoiding any single maintainer or foundation holding rights to all the copyrights. So relicensing capability may or may not be a factor, though I'd argue it almost always should be, for future proofing.

However, I wouldn't want to exclude copyleft projects that also want the other benefits of a CLA, like assurances around rights to license, process for employer/client work, and some affirmative evidence of developer intent to license.
